# Numpy

Numpy es la librería principal que usamos para cálculo científico. Esta nos proporciona un nuevo tipo de dato "Numpy Array" y herramientas para trabajar con el.

## Importando la librería numpy

In [1]:
import numpy as np

## Creando arrays a partir de listas 

Podemos hacer uso de **np.array** para crear arrays a partir de listas.

In [4]:
#Nos creamos un array de números enteros 
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

Debemos de recordar que a diferencia que las listas, Numpy está restringido a arrays que contengan el mismo tipo de variables. Si los tipos no son iguales, Numpy inferirá si es posible el tipo de dato.

In [7]:
#Crear un numpy array de 4 elementos que contenga números enteros y de tipo float, observar el resultado

In [5]:
# Ejercicio 1.
np.array([1,2,3,4.5])

array([1. , 2. , 3. , 4.5])

Como podemos ver, numpy transforma el menos restrictivo, int, al mas, float.

Si queremos especificar el tipo de dato resultante que queremos que almacene el array, podemos hacer uso del argumento **dtype**.

In [5]:
np.array([3.14, 3, 1.15, 2], dtype = 'int32')

array([3, 3, 1, 2], dtype=int32)

Podemos crear arrays multidimensionales a partir de listas de listas, a continuación vamos a proceder a crearnos un array 2D.

In [6]:
np.array([[1,2], [2,3], [3,4]])

array([[1, 2],
       [2, 3],
       [3, 4]])

## Creando arrays desde cero

A la hora de crear arrays de una mayor dimensión, es más eficiente crear arrays desde cero usando rutinas que ya están disponibles en Numpy.

In [9]:
#Nos creamos una array de una dimensión, de 10 elementos donde todos ellos serán ceros
print(np.zeros(10, dtype = "int"))
print(np.zeros([10,10], dtype = 'int'))

[0 0 0 0 0 0 0 0 0 0]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


La función np.ones nos permite crear matrices de forma similar a np.zeros, para ello disponemos de **np.ones()**. Como primer parámetros le pasamos en forma de tupla la dimensión de nuestra array  y mediante el comando dtype indicamos el tipo de dato.

In [11]:
#Crear un numpy array donde todos sus elementos sean unos y además el tipo de dato sea de tipo float
print(np.ones(5, dtype = 'float'))
print(np.ones([3,3], dtype = 'float'))

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


La función **np.full()** nos permite crear un array donde todos sus elementos sean un valor que nosotros le indicamos. Esta función como primer parámetro recibe en forma de tupla la dimensión del array que queremos crear, como segungo parámetro recibe el valor que queremos que reciba nuestra array. Dispone también del parámetro **dtype** que nos permite indicar el tipo de dato.

In [12]:
#Crear un array de dimensión 3x3 donde todos sus elementos tomen el valor 3.1415 
np.full([3,3], 3.1415)

array([[3.1415, 3.1415, 3.1415],
       [3.1415, 3.1415, 3.1415],
       [3.1415, 3.1415, 3.1415]])

La función **np.arange()** se trata de una función que nos permite crear un array que tome valores entre dos valores indicados, con un paso también indicado según nos convenga. En su forma más básica la llamada sería **np.arange(start, stop, step)**. Debemos recordar que el valor **stop** no se incluye en nuestro array. En caso de no indicar el valor de start este tomará por defecto el valor 0 y el step tomará por defecto el valor de 1.

In [16]:
#Crear un array que empiece en 0 y termine en 20 c0n pasos de 2
np.arange(1,3,0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

La función **np.linspace()** nos permite crear un array con valores equidistantes. En su forma más básica la llamda sería **np.linspace(start, stop, num_elementos)**.

In [17]:
#Crear un array con 20 elementos equidistantes entre 0 y 10.
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

La función **np.random.random()** nos permite crear un array que toma valores aleatorios uniformemente distribuidos. En su forma más básica esta función recibe en forma de tupla el tamaño del array.

In [22]:
#Crear un array de tamaño 3x3 cuyos valores estén uniformemente distribuidos.
np.random.random([2,2])

array([[0.13813531, 0.93334587],
       [0.03729996, 0.23738954]])

La función **np.random.normal()** nos permite crear un array que sigue una distribución normal con una desviación y una media seleccionadas. Eta función recibe como primer parámetro la desviación, como segundo parámetro la media y como tercer parámetro y en forma de tupla la dimensión de nuestra distribución.

In [23]:
#Crear un array que cuyos valores sigan una distribución normal con desviación 1, media 0 y de dimensión 3x3.
np.random.normal(0,1,[2,2])

array([[ 0.19304408,  0.61679138],
       [-0.01353773,  0.07917265]])

In [25]:
def myFunction(x):
    '''In this function this is
    
    - Some documentation
    
    - **in a weird** 
        - Order
            - Of indexing
    :hello:
    
    .. note::
        Something
    '''
    pass

In [26]:
help(myFunction)

Help on function myFunction in module __main__:

myFunction(x)
    In this function this is
    
    - Some documentation
    
    - **in a weird** 
        - Order
            - Of indexing
    :hello:
    
    .. note::
        Something



La función **np.random.randint()**, nos permite crear arrays de números aleatorios de tipo entero, entre dos números enteros. Su llamada más básica puede realizarse como: **np.random.randint(stop, start, size)**. En caso de que el array sea de una sola dimensión mediante el parámetro size indicamos el número de elementos de nuestro array.

In [19]:
#Crear un array de dimensión 3x3 cuyos valores sean números enteros entre 0 y 8
np.random.randit

La función **np.eye()** nos permite crear la matriz identidad. Esta función en su forma más básico recibe como parámetros la dimensión de nuestra matriz identidad.

## Atributos en los tipos de datos Numpy

Los atributos nos permiten determinar el tamaño, la forma, la ocupación en memoria y el tipo de dato de un array.

In [20]:
#Generar tres arrays de números enteros: la primera se llamará x1 y será de una dimensión, la segunda se llamará
#x2 y será de dos dimensiones (3x3) y la tercera se llamará x3 y será de tres dimensiones (3,4,5).
np.ra

Cada una de estas arrays dispone de los siguientes atributos:

* ndim: nos permite saber la dimensión de nuestra array

* shape: nos permite conocer el tamaño de nuestra array

* size: nos permite conocer el número de elementos de nuestra array

* dtype: nos permite conocer el tipo de dato de cada uno de los elementos de nuestra array

* itemsize: nos permite conocor el tamaño de cada uno de los elementos de nuestra array

* nbytes: nos permite conocer el tamaño total de nuestra array

## Indexando Arrays: accediendo a elementos individuales

Al igual que en las listas, podemos acceder al elemento **i** de un array 1-dimensional, haciendo uso de los corchetes y el índice en el que se encuentra el valor al cual deseamos acceder.

In [15]:
#Accedemos al primer elemento de x1
x1 = np.array([[1,2,3],[5,6,7]])
print(x1.shape)
print(x1.ndim)
print(x1.size)
print(x1.dtype)
print(x1.nbytes)
x1

(2, 3)
2
6
int32
24


array([[1, 2, 3],
       [5, 6, 7]])

In [14]:
#Accedemos al quinto valor de x1
x1[1] # Por filas

array([5, 6, 7])

In [25]:
# Acceder a unos cuantos valores de la primera fila
x1[1,:2] # Desde el principio hasta el 2, sin incluirlo

array([5, 6])

In [26]:
x1[1, -1] # number

7

Python nos permite hacer uso de índices negativos a la hora de recorrer un array de forma inversa. De forma que si queremos acceder al último elemento de un array hacemos uso del índice -1.

In [28]:
#Accedemos al penúltimo valor de x1 haciendo uso del indexado negativo

En caso de arrays multidimensionales, al igual que se hace en R podemos acceder a un determinado elemento indicando la fila y la columna en la cual se encuentra el elemento al cual deseamos acceder. Para ello le pasamos en forma de tupla la fila y la columna a la cual deseamos acceder, haciendo uso de la notación de los corchetes.

In [29]:
#Accedemos al elemento de la fila 2 y la columna 2 de x2

In [30]:
#Accedemos al elemento que se encuentra en la última fila y en la última columna de x2, haciendo uso del indexado
#negativo.

A la hora de modicar valores en un array vasta con seleccionar el elemento que deseamos cambiar y asignarle el nuevo valor deseado.

In [31]:
#Seleccionamos el elemento de la fila 1 y la columna 1 de x2 y le asignamos un nuevo valor.

## Recorriendo arrays: accediendo a subarrays

Si bien la notación anterior nos permite acceder a elementos individuales, numpy permite el indexado mediante rebanadas (slices), para ello podemos hacer uso de la notación de los dos puntos (start:end:step). El valor de end no está incluido entre los elementos seleccionados.

In [32]:
#Generamos un array con valores del 1 al 10 (hacer uso de np.arange)

In [35]:
#Accedemos a los elementos que se encuentran entre la posición 2 y 5 estando el último valor incluido

In [34]:
#Accedemos a los elementos que se encuentran entre la posición 7 y 10 sin estar este último valor incluido

Si queremos seleccionar todos los elementos a partir de un elemento determinado podemos hacer uso de la notación **start:**. Si por el contrario lo que queremos es seleccionar desde el primer elemento hasta un determinado elemento podemos hacer uso de **:end**. La notación **start::step** nos permite seleccionar los elementos desde la posición en pasos en los pasos indicados por step.

In [28]:
#Seleccionamos los elementos desde el 4 hasta el último de x1
print(x1)
print(x1[1, ::2]) # Cada dos

[[1 2 3]
 [5 6 7]]
[5 7]


In [37]:
#Seleccionamos los elementos desde el primero hasta el 6 de x1

In [38]:
#Seleccionamos los elementos impares haciendo uso de la notación start::step

## Arrays multidimensionales

Lo visto anteriormente también es válido para arrays multi-dimensionales.

In [42]:
#Seleccionamos las dos primeras filas y las tres primeras columnas de x2

In [43]:
#Seleccinamos todas filas y las dos primeras columnas

In [44]:
#Invertimos los números de nuestra matriz (la notacion ::step selecciona todos los elementos de una matriz en los 
#pasos indicados)

## Copias de arrays 

Debemos tener claro que a la hora de seleccionar un subarray dentro de un array esta no genera copias. Es decir, nuestro puntero sigue apuntando a nuestra array original.

In [45]:
#Muestra el array original x2

In [46]:
#Create una nueva variable llamada x2_sub que contenga las dos primeras filas y las dos primeras columnas de x2

In [47]:
#Cambia en x2_sub el valor del primer elemento

In [48]:
#Muestra nuevamente el array original x2

Si lo que deseamos es mantener intacta nuestra array original podemos hacer uso del atributo **copy()** de los objetos numpy array. Este objeto nos crea una copia .

In [49]:
#Create una nueva variable llamada x2_copy que sea una copia de x2

In [50]:
#Cambia en x2_copy el valor del primer elemento

In [51]:
#Muestra x2_copy 

In [52]:
#Muestra x2

## Reshape arrays

**reshape()** nos permite cambiar la dimensión de nuestro array. Para que este comando funcione de forma adecuada la nuev dimensión debe coincidir con el número de elementos de nuestra array original. Si el argumento de reshape toma el valor de -1 se traduce en un array de longitud igual al número de elementos del array.

In [34]:
#Nos creamos un array con los numeros del 1 al 10 este último sin incluir
print(x1)
print(x1.reshape([3,2]))
print(x1)

[[1 2 3]
 [5 6 7]]
[[1 2]
 [3 5]
 [6 7]]
[[1 2 3]
 [5 6 7]]


In [54]:
#Convertimos esta array en un array 3x3

## Concatenando arrays

La concatenación o la unión de múltiples arrays en Numpy, se lleva a cabo principalmente haciendo uso de las rutinas: **np.concatenate**, **np.vstack** y **np.hstack**.

La función np.concatenate toma una tupla o lista de arrays y las concatena.

In [57]:
#Generar un array que contenga los elementos 1,2,3 llamada x. Generar otra array llamada y que contenga los 
#elementos 3,2,1 en el orden indicado.

In [58]:
#Concatenar las arrays x e y

Podemos concatenar tantas arrays como queremos.

In [59]:
#Generar un array z que contenga entre 0 y 1 5 números equiespaciados.

In [60]:
#Concatenar las arrays x,y,z

Podemos concatenar incluso arrays de más de una dimensión.

In [62]:
#Generar un numpy array de dimensión 2x3 que contenga los valores 1,2,3,4,5,6 llamada aux

In [63]:
#Concatenar dicha array consigo misma

También podemos concatenar a lo largo del eje horizontal, para ello basta con hacer uso del parámetro **axis = 1** de la función **np.concatenate()**

In [64]:
#Concatenar el array aux consigo misma haciendo uso de axis = 1.

A la hora de trabajar con arrays de dimensiones mixtas, puede ser una mejor opción hacer uso de las funciones **np.vstack **(vertical stack) y **np.hstack** (horizontal stack). Como parámetro se le pasa una tupla que contienen las arrays a concatenar.

In [65]:
#Generar un array de 1 dimensión con los elementos 1,2,3 llamada x. Generar un array llamada y de dimensión 2x3 con
#donde la primera fila tenga los valores 9,8,7 y la segunda fila tenga los valores 6,5,4.

In [71]:
#Concatenar haciendo uso de np.vstack

array([1, 2, 3, 9, 8, 7, 6, 5, 4])

In [72]:
#Modificar el código anterior para poder hacer uso de np.hstack con el código anterior.

Concatenar arrays

In [50]:
print('We\'got x1: \n \n', x1, '\n')
z = x1.copy()
print(z, '\n')

print(np.concatenate([x1,z]), '\n')
print(np.concatenate([x1,z],axis = 1))

We'got x1: 
 
 [[1 2 3]
 [5 6 7]] 

[[1 2 3]
 [5 6 7]] 

[[1 2 3]
 [5 6 7]
 [1 2 3]
 [5 6 7]] 

[[1 2 3 1 2 3]
 [5 6 7 5 6 7]]


## Separando arrays

La separación de arrays están implementadas mediante las funciones, **np.split()**, **np.vsplit()** y **np.hsplit()**. A cada una de estas funciones le pasamos el array y los índices en los cuales queremos realizar el split.

In [73]:
#Nos creamos un array
x = np.arange(1,20,0.5)

#Procedemos a splitear nuestra array en tres arrays diferentes separadas en los índices 9 y 15
i, j, k = np.split(x, (9, 15))

In [52]:
i, j = [[1],[2]]

In [53]:
print(i,j)

[1] [2]


In [78]:
#Nos creamos un array
grid = np.arange(16).reshape((4,4))

#Hacemos uso de np.vsplit  y cortamos por la fila 2
print(np.vsplit(grid, [2]))

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [ ]:
### Hacemos uso de np.hsplit y cortamos por la columna 2
print(np.hsplit(grid, [2]))

# Computando con Numpy Arrays: funciones universales

A la hora de realizar operaciones con Numpy arrays esta puede ser o extremadamente rápida o muy lenta, la clave para que las operaciones se realicen de forma eficiente es hacer uso de la vectorización. La vectorización está implementada en las funciones universales.

## Lentitud de los bucles

Debido a que los tipos de datos en Python son flexible, esto da lugar a que ciertas operaciones no puedan ser ejecutadas por debajo en código C o Fortran. La lentitud relativa de Python queda de manifiesta en pequeñas operaciones en las cuales se repiten determinadas operaciones.

In [56]:
#Fijamos la semilla
np.random.seed(0)

#Generamos la función que calcula la inversa de cada número para un array
def calcula_inversa(array):
    output = np.empty(len(array))
    for i in range(len(array)):
        output[i] = 1.0 / array[i]
    return output

#Hacemos la llamada a la función
result = calcula_inversa(np.random.randint(1, 10, size = 5))
print(result)

[0.16666667 1.         0.25       0.25       0.125     ]


Parece ser que todo va bien, sin embargo si trabajamos con arrays de una elevada dimensión...

In [57]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit calcula_inversa(big_array)

2.39 s ± 97 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Lo que está pasando es que cada vez que el valor inverso de un número es calculado, Python primero chequea el tipo de objeto y tras esto busca de forma dinámica la función correcta para operar sobre dicho tipo de dato. Si estuviésemos trabajado sobre código compilado, este tipo de dato sería conocido antes de ejecutar el código y el resultado se podría calcular de una forma mucha más eficieente.

## Introducción a las funciones universales

Para determinadas operaciones Python ofrece una serie de rutinas que son tipadas estáticamente y compiladas. Estas son las denominadas operaciones vectorizadas. Estas operaciones son ejecutadas bajo una campa compilada que subyace a Numpy, lo que hace que las operaciones sean mucho más eficientes.

In [58]:
#Fijamos la semilla
np.random.seed(0)
aux = np.random.randint(1, 10, size = 5)
#Comparemos el resultado haciendo uso de la vectorización y sin usar la vectorización
print(calcula_inversa(aux))
print(1.0 / aux)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


Veamos ahora la diferencia de tiempos con el array de gran dimensión

In [59]:
%timeit (1.0 / big_array)

6.52 ms ± 242 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


**Hacer uso de las funciones universales es mucho más eficiente que ejecutar operaciones mediante bucles, especialmente cuando el array es de una dimensión realmente elevada. Siempre que implementemos un bucle en Python, deberíamos considerar en vectorizar dicho bucle.**

## Especificando la salida

Cuando estamos realizando operaciones entre arrays de una elevada dimensionalidad, especificar el lugar en el cuál queremos almacenar el resultado de la operación puede resultar bastante conveniente. En lugar de crear una matriz temporal para almacenar el resultado de la operación, podemos escribir estos datos directamente en memoria, para esto las funciones universales disponen del argumento **out**.

In [9]:
#Generamos un array
x = np.arange(5)

#Nos creamos un array de dimensión 10 de ceros
z = np.zeros(10)

#Ahora procedemos a escribir en las posiciones pares el valor de la expresión 2^x
np.power(2, x, out = z[::2])
print(z)

[  1.   0.   2.   0.   4.   0.   8.   0.  16.   0.]


Si hubiesemos realizado z[::2] = np.power(2, x), en este caso esto se generaría un array temporal para almecenar el resultado,  seguido de una segunda operación que lo que hace es copiar estos valores en la matriz z.

In [67]:
# Prueba pyhon
from timeit import default_timer as timer

start = timer()
# Mal
n = 1000000
z = np.zeros(n)
x = np.full(n, 7)
z = np.power(x, 2)
end = timer()
print('BAD WAY:', end - start) # Time in seconds, e.g. 5.38091952400282

start = timer()
# Mal
n = 1000000
z = np.zeros(n)
x = np.full(n, 7)
np.power(x, 2, out = z)
end = timer()
print('GOOD WAY:', end - start) # Time in seconds, e.g. 5.38091952400282




BAD WAY: 0.010875481999391923
GOOD WAY: 0.011799380000411475


In [41]:
help(np.power)

Help on ufunc object:

power = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array

## Agregaciones

Algunas funciones universales disponen de una serie de funciones de agregación que pueden a llegar a ser muy interesantes. Por ejemplo **reduce()** aplicada sobre una función universal nos comprime el resultado en una única dimensión aplicando la función universal indicada.

In [10]:
#Hacemos uso de la función reduce, para obtener la suma de todos los elementos de un array
x = np.arange(5)
print(np.add.reduce(x))

10


De forma similar, si hacemos uso de **reduce** sobre **np.multiply()** esto nos retorna el producto total de los elementos.

In [70]:
x = np.arange(1,6)
help(np.multiply.reduce)
print(np.multiply.reduce(x))

Help on built-in function reduce:

reduce(...) method of numpy.ufunc instance
    reduce(a, axis=0, dtype=None, out=None, keepdims=False, initial)
    
    Reduces `a`'s dimension by one, by applying ufunc along one axis.
    
    Let :math:`a.shape = (N_0, ..., N_i, ..., N_{M-1})`.  Then
    :math:`ufunc.reduce(a, axis=i)[k_0, ..,k_{i-1}, k_{i+1}, .., k_{M-1}]` =
    the result of iterating `j` over :math:`range(N_i)`, cumulatively applying
    ufunc to each :math:`a[k_0, ..,k_{i-1}, j, k_{i+1}, .., k_{M-1}]`.
    For a one-dimensional array, reduce produces results equivalent to:
    ::
    
     r = op.identity # op = ufunc
     for i in range(len(A)):
       r = op(r, A[i])
     return r
    
    For example, add.reduce() is equivalent to sum().
    
    Parameters
    ----------
    a : array_like
        The array to act on.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a reduction is performed.
        The default (`axis` = 0) is perform a re

Si queremos obtener los pasos intermedios podemos hacer uso de **accumulate()**.

In [12]:
#Vemos el resultado de hacer uso de np.add con accumulate
print(np.add.accumulate(x))

[ 1  3  6 10 15]


In [13]:
#Vemos el resultado de aplicar accumulate con np.multiply
print(np.multiply.accumulate(x))

[  1   2   6  24 120]


In [14]:
np.arange(1, 6)

array([1, 2, 3, 4, 5])

## Eficiencia de Numpy respecto a funciones nativas de Python

A la hora de realizar operaciones como la suma, mínimo, máximo etc Python dispone de sus propias funciones nativas. Sin embargo debido a que numpy corre bajo código compilado es mucho más eficiente.

In [68]:
#Nos generamos un array
big_array = np.random.randint(1, 100, size=1000000)

#Hacemos la medida de tiempos
%timeit sum(big_array)
%timeit np.sum(big_array)
%timeit np.add.reduce(big_array)

90.1 ms ± 4.95 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
549 µs ± 18.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
568 µs ± 36.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [17]:
%timeit min(big_array)
%timeit np.min(big_array)

68.3 ms ± 1.38 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.1 ms ± 10.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [18]:
%timeit max(big_array)
%timeit np.max(big_array)

63 ms ± 253 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.09 ms ± 17.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
