# *Definitive Guide to NumPy*

- Creador: &emsp;&emsp;&emsp;&emsp;&emsp; Ricardo Recarey Fernández [(LinkedIn)](https://www.linkedin.com/in/richyrecarey/)
- Creación: &emsp;&emsp;&emsp;&emsp;&emsp;2019-10-11  
- Última modificación: &nbsp;2019-10-11

In [4]:
# Imports básicos
import sys

import numpy as np
print(f"NumPy version:  {np.__version__}")
print(f"Python version: {sys.version}")

NumPy version:  1.16.2
Python version: 3.6.8 |Anaconda custom (64-bit)| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]


# 1. Cosas básicas

La estructura principal de numpy es el array

In [17]:
arr = np.array([1,2,3])
print(arr, " <-> ",type(arr)," <-> ", arr.dtype, " <-> ", arr.shape)

[1 2 3]  <->  <class 'numpy.ndarray'>  <->  int32  <->  (3,)


In [18]:
# Se puede crear con el tipo que queramos!
arr = np.array([1,2,3], dtype = 'float64')
print(arr, " <-> ",type(arr)," <-> ", arr.dtype, " <-> ", arr.shape)

[1. 2. 3.]  <->  <class 'numpy.ndarray'>  <->  float64  <->  (3,)


Obviamente, en este caso estamos hablando de arrays *unidimensionales*, y por eso su 'shape' es de la forma (a, ). También podemos crear arrays multidimensionales, de la 'shape' que nos convenga:

In [20]:
np.array([[1,2], 
          [1,2]]).shape

(2, 2)

In [22]:
np.array([[[1,2],[1,2]], 
          [[1,2],[1,2]]]).shape

(2, 2, 2)

In [47]:
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)

[1. 2. 3.]
(3,)
1
3
float64
8
24


In [48]:
arr = np.zeros([2,2, 2], dtype = 'int')

print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)

[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]
(2, 2, 2)
3
8
int32
4
32


## 1.1. Creación con métodos preestablecidos

Existen los métodos **zeros, ones, full, etc**

In [25]:
print(np.zeros([2,2, 2], dtype = 'int'))

[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]


In [26]:
print(np.full([2,2, 2], 2))

[[[2 2]
  [2 2]]

 [[2 2]
  [2 2]]]


Creación de arrays de una dimensión

In [29]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [30]:
# Equidistantes con longuitud 10!
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

### 1.1.1. Generación de números aleatorios:

In [31]:
np.random.random(1)

array([0.09920255])

In [35]:
np.random.random([2,2])

array([[0.74258715, 0.64975211],
       [0.85416397, 0.00992069]])

In [36]:
# mu, sigma, shape
np.random.normal(0,1, [2,2])

array([[-0.3666969 , -0.99209541],
       [ 0.73664205,  0.57315903]])

In [43]:
# Desde, hasta, longuitud
np.random.randint(1,10,3)

array([5, 4, 7])

AttributeError: module 'numpy' has no attribute 'ra'

# 2. Reshape

In [63]:
print(arr,"\n")
print(arr.reshape(-1,1))
print(arr.reshape(-1,1).shape, "\n")
print(arr.reshape(1,-1))
print(arr.reshape(1,-1).shape)

[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]] 

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
(8, 1) 

[[0 0 0 0 0 0 0 0]]
(1, 8)


In [73]:
x = np.array([1,2,3,4,5])
print(x.reshape(-1,1))
print(x.reshape(-1,1).shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)
